# Site settings
title: tl;dr
subtitle: concentrated like a poem
email: xy124@noreply.github.com
#description: ""
baseurl: ""
url: "http://xy124.github.io"
#twitter_username:
github_username:  xy124
plugins:
  - jekyll-feed

# Build settings
markdown: kramdown
permalink: pretty
